#pragma once

#include <iostream>
#include <vector>
#include <string>
#include <limits>
#include <iomanip>
#include <algorithm>
#include <random>
#include <fstream>
#include <sstream>
#include <chrono>
#include <string_view>

using std::cout;
using std::cin;
using std::endl;
using std::vector;
using std::string;
using std::ostream;
using std::ifstream;
using std::ofstream;
using std::left;
using std::setw;
using std::fixed;
using std::setprecision;
using std::string_view;
using std::sort;
using std::istringstream;